/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BoardGameRequest } from './models/board-game-request';
export type { BoardGameResponse } from './models/board-game-response';
export type { PageResponseBoardGameResponse } from './models/page-response-board-game-response';
export type { PageResponseReviewResponse } from './models/page-response-review-response';
export type { RegistrationRequest } from './models/registration-request';
export type { ReviewRequest } from './models/review-request';
export type { ReviewResponse } from './models/review-response';
