/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { BoardGameRequest } from './models/board-game-request';
export { BoardGameResponse } from './models/board-game-response';
export { PageResponseBoardGameResponse } from './models/page-response-board-game-response';
export { PageResponseReviewResponse } from './models/page-response-review-response';
export { RegistrationRequest } from './models/registration-request';
export { ReviewRequest } from './models/review-request';
export { ReviewResponse } from './models/review-response';
export { UpdateRatingRequest } from './models/update-rating-request';
