/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ReviewsService } from './services/reviews.service';
export { BoardGameService } from './services/board-game.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
