services:
  postgres:
    container_name: postgres-sql-bgr
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: SmallSocialNetworkDB
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bgr
    image: maildev/maildev
    ports:
      - 1080:1080  #for web service
      - 1025:1025  #for SMTP (simple mai transfer protocol)


networks:
  spring-demo:
    driver: bridge  #lets containers from the same network communicate, and isolates them from containers
                    #from other networks


volumes:   #used for persistent data, if the app fails, the data still exists
  postgres:
    driver: local
