services:
  postgres:
    container_name: postgres-sql-bgr
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: SmallSocialNetworkDB
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  mail-dev:
    container_name: mail-dev-bgr
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - spring-demo

  spring-app:
    container_name: spring-app-bgr
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8088:8088
    networks:
      - spring-demo
    environment:
      SPRING_PROFILES_ACTIVE: dev

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
