/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseBoardGameResponse } from '../../models/page-response-board-game-response';

export interface FindMyWishlistedBoardGames$Params {
  page?: number;
  size?: number;
}

export function findMyWishlistedBoardGames(http: HttpClient, rootUrl: string, params?: FindMyWishlistedBoardGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseBoardGameResponse>> {
  const rb = new RequestBuilder(rootUrl, findMyWishlistedBoardGames.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseBoardGameResponse>;
    })
  );
}

findMyWishlistedBoardGames.PATH = '/boardgame/wishlist';
