/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseReviewResponse } from '../../models/page-response-review-response';

export interface FindAllReviewsByBoardGame$Params {
  'boardgame-id': number;
  page?: number;
  size?: number;
}

export function findAllReviewsByBoardGame(http: HttpClient, rootUrl: string, params: FindAllReviewsByBoardGame$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseReviewResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllReviewsByBoardGame.PATH, 'get');
  if (params) {
    rb.path('boardgame-id', params['boardgame-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseReviewResponse>;
    })
  );
}

findAllReviewsByBoardGame.PATH = '/reviews/boardgame/{boardgame-id}';
