/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BoardGameResponse {
  archived?: boolean;
  coverImage?: Array<string>;
  description?: string;
  developer?: string;
  id?: number;
  owner?: string;
  publisher?: string;
  rating?: number;
  shareable?: boolean;
  title?: string;
  wishlisted?: string;
}
