/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BoardGameRequest {
  description: string;
  developer: string;
  id?: number;
  publisher: string;
  shareable?: boolean;
  title: string;
}
